name: MobEscape
version: '${project.version}'
main: xyz.mlserver.mobescape.MobEscape
depend:
    - WorldEdit
    - Citizens
    - PlaceholderAPI

commands:
    mobescape:
        description: MobEscape command
        aliases: [me]
        permission: mobescape.command